### ISSUE TITLE
OpCode not supported: LdFtn

### ISSUE THREAD

**Issue by Dentrax** [icsharpcode/ILSpy#1104]
I've just encountered this problem when I'm surfing on the Assembly file. (Unity-Mono)

How ILSpy (3.1.0.3599-beta1) decompile: https://pastebin.com/JnWvGjPY

How dnSpy (v4.5.2) decompile: https://pastebin.com/NULLjY3Q

We known dnSpy is an ILSpy-based decompiler, but I don't figure out why it's decompile properly&regular.

Specifically, delegate-objects are not properly decompile. And please take a look;

https://github.com/0xd4d/dnSpy/issues/694
https://github.com/0xd4d/dnSpy/issues/737

**Comment by siegfriedpammer** [comment]
Could you provide the assembly (including references!) that is not properly decompiled? Thank you very much!

**Comment by Dentrax** [comment]
I guess it can't find the necessary reference. I don't know why. dnSpy finds references in the same directory, but ILSpy not. (even i ran in admin-privileges)

You can download compiled Unity's Managed folder here: http://www.mediafire.com/file/0xqcsg11k4q4deb/Issue1104.rar

Assembly-CSharp.dll / HeyzapTest.cs // InitHeyzap()

**Comment by siegfriedpammer** [comment]
Thanks! It seems this is fixed in the latest nightly build (tested with 3.1.0.3635-beta2). Can you confirm using the latest nightly build? It seems though, you provided a different assembly than used in the example above, because the first line is completely different...

> I guess it can't find the necessary reference. I don't know why. dnSpy finds references in the same directory, but ILSpy not. (even i ran in admin-privileges)

Admin should have no impact at all because we're not requesting write access. Also, on my machine ILSpy had no problem finding all the references.

(the number of gotos could be reduced by reordering the blocks @dgrunwald what do you think?)

```
// HeyzapTest
using Heyzap;
using UnityEngine;

private void InitHeyzap()
{
	HeyzapAds.Start("b8fdab463806cd00179e846212d4e544", 0);
	HZIncentivizedAd.AdDisplayListener displayListener = delegate(string adState, string adTag)
	{
		if (adState.Equals("show"))
		{
			callBacksReceived = true;
		}
		if (!adState.Equals("hide"))
		{
			goto IL_0027;
		}
		goto IL_0027;
		IL_0064:
		if (!adState.Equals("fetch_failed"))
		{
			goto IL_0074;
		}
		goto IL_0074;
		IL_0074:
		if (adState.Equals("incentivized_result_complete"))
		{
			Time.timeScale = 1f;
			Debug.Log("Heyzap Rewarded ad incentivized_result_complete");
			base.Invoke("DelayInReward", 1f);
		}
		if (adState.Equals("incentivized_result_incomplete"))
		{
			UIManager._instance.ShowAGenericMessage("Something went wrong. You might have cancelled the video Ad or there was a network issue");
			UIManager._instance.ToggleLoadingScreen(false);
			UIManager._instance.ToggleGameOverScreen(true);
			UIManager._instance.gameOverScreen.noOfChancesLeftToUseContinue++;
		}
		if (!adState.Equals("audio_starting"))
		{
			goto IL_0104;
		}
		goto IL_0104;
		IL_0027:
		if (!adState.Equals("click"))
		{
			goto IL_0037;
		}
		goto IL_0037;
		IL_0037:
		if (adState.Equals("failed"))
		{
			callBacksReceived = true;
			ShowAdNotAvailable();
		}
		if (!adState.Equals("available"))
		{
			goto IL_0064;
		}
		goto IL_0064;
		IL_0104:
		if (!adState.Equals("audio_finished"))
		{
			return;
		}
	};
	HZIncentivizedAd.SetDisplayListener(displayListener);
	HZInterstitialAd.AdDisplayListener displayListener2 = delegate(string adState, string adTag)
	{
		if (!adState.Equals("show"))
		{
			goto IL_0010;
		}
		goto IL_0010;
		IL_0010:
		if (adState.Equals("hide"))
		{
			Time.timeScale = 1f;
			GameManager.instance.InterstitialNotAvailableRestartGame();
			UIManager._instance.ToggleCommericalBreakPanel(false);
			UIManager._instance.PauseGame();
		}
		if (!adState.Equals("click"))
		{
			goto IL_0059;
		}
		goto IL_0059;
		IL_0098:
		if (!adState.Equals("fetch_failed"))
		{
			goto IL_00a8;
		}
		goto IL_00a8;
		IL_00a8:
		if (!adState.Equals("audio_starting"))
		{
			goto IL_00b8;
		}
		goto IL_00b8;
		IL_0059:
		if (adState.Equals("failed"))
		{
			Time.timeScale = 1f;
			UIManager._instance.ToggleCommericalBreakPanel(false);
			GameManager.instance.InterstitialNotAvailableRestartGame();
		}
		if (!adState.Equals("available"))
		{
			goto IL_0098;
		}
		goto IL_0098;
		IL_00b8:
		if (!adState.Equals("audio_finished"))
		{
			return;
		}
	};
	HZInterstitialAd.SetDisplayListener(displayListener2);
	HZIncentivizedAd.Fetch();
}
```

**Comment by Dentrax** [comment]
> It seems though, you provided a different assembly than used in the example above, because the first line is completely different...

I didn't use another Assembly file. It was completely original. :) Here;

![asdsadasdsa](https://user-images.githubusercontent.com/16493751/37901192-30fce4ca-30f9-11e8-9d3b-703b077318f9.png)

Unrelated to this issue;

I also can't get successfull build from ILSpy project. I did a lot of research, but it didn't work out. It says me "ILSpy debug profile doesn't exist." But I don't understand, it looks fine;

![sdasdsa](https://user-images.githubusercontent.com/16493751/37901396-c20de0c2-30f9-11e8-8cec-df0d773a528f.png)

My Rebuild Output:

```
1>------ Rebuild All started: Project: ICSharpCode.TreeView, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ICSharpCode.Decompiler, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: Mono.Cecil, Configuration: net_4_0_Debug Any CPU ------
3>  Mono.Cecil -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\cecil\bin\net_4_0_Debug\Mono.Cecil.dll
4>------ Rebuild All started: Project: Mono.Cecil.Pdb, Configuration: net_4_0_Debug Any CPU ------
4>  Mono.Cecil.Pdb -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\cecil\bin\net_4_0_Debug\Mono.Cecil.Pdb.dll
1>ICSharpCode.TreeView -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\SharpTreeView\bin\Debug\net46\ICSharpCode.TreeView.dll
2>ILSpyUpdateAssemblyInfo1487548582
2>ILSpyUpdateAssemblyInfo1487548582
2>ILSpyUpdateAssemblyInfo1487548582
2>True
2>0
2>True
2>0
2>ICSharpCode.Decompiler -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ICSharpCode.Decompiler\bin\Debug\net46\ICSharpCode.Decompiler.dll
2>ICSharpCode.Decompiler -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ICSharpCode.Decompiler\bin\Debug\net45\ICSharpCode.Decompiler.dll
2>ICSharpCode.Decompiler -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ICSharpCode.Decompiler\bin\Debug\netstandard2.0\ICSharpCode.Decompiler.dll
2>Successfully created package 'C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ICSharpCode.Decompiler\bin\Debug\ICSharpCode.Decompiler.3.1.0.3637-beta2-debug.nupkg'.
5>------ Rebuild All started: Project: ILSpy, Configuration: Debug Any CPU ------
6>------ Rebuild All started: Project: ICSharpCode.Decompiler.Tests, Configuration: Debug Any CPU ------
6>TestCases\Correctness\Async.cs(256,23,256,25): warning CS0168: The variable 'ex' is declared but never used
6>ICSharpCode.Decompiler.Tests -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ICSharpCode.Decompiler.Tests\bin\Debug\net46\ICSharpCode.Decompiler.Tests.exe
6>Done building project "ICSharpCode.Decompiler.Tests.csproj".
5>ILSpy -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ILSpy\bin\Debug\net46\ILSpy.exe
7>------ Rebuild All started: Project: ILSpy.BamlDecompiler, Configuration: Debug Any CPU ------
8>------ Rebuild All started: Project: TestPlugin, Configuration: Debug Any CPU ------
8>TestPlugin -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\TestPlugin\bin\Debug\net461\Test.Plugin.dll
7>ILSpy.BamlDecompiler -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ILSpy\bin\Debug\net46\ILSpy.BamlDecompiler.Plugin.dll
9>------ Rebuild All started: Project: ILSpy.BamlDecompiler.Tests, Configuration: Debug Any CPU ------
10>------ Rebuild All started: Project: ILSpy.AddIn, Configuration: Debug Any CPU ------
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Utilities" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Imaging" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
10>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Threading" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
10>ILSpy.AddIn -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ILSpy.AddIn\bin\Debug\net46\ILSpy.AddIn.dll
10>Done building project "ILSpy.AddIn.csproj".
9>ILSpy.BamlDecompiler.Tests -> C:\Users\Furkan\Documents\GitHub Projects\ILSpy\ILSpy.BamlDecompiler.Tests\bin\Debug\net46\ILSpy.BamlDecompiler.Tests.dll
========== Rebuild All: 10 succeeded, 0 failed, 0 skipped ==========
```

**Comment by siegfriedpammer** [comment]
I can tell from your screenshot, that your are not using the latest nightly build (please get it from here: https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy_binaries.zip?branch=master&job=Configuration%3A+Release)

The build issue is strange... seems you added the submodules as well... which version of VS are you using?

**Comment by Dentrax** [comment]
I tested the lastest build, but unfortunately it can't find the references. Also, LdFtn error still there. :(

VS Version:
```
Microsoft Visual Studio Enterprise 2017 
Version 15.5.5
VisualStudio.15.Release/15.5.5+27130.2026
Microsoft .NET Framework
Version 4.7.02556
```

**Comment by siegfriedpammer** [comment]
You could try changing the project debug options, see the "Debug" section. There have been some breaking changes in VS 2017 (15.6), which might be related to this issue.

**Comment by siegfriedpammer** [comment]
Regarding the LdFtn issue: could you provide another example binary?

**Comment by Dentrax** [comment]
My debug panel settings are exactly the same as yours. :(

Unfortunately, this is the first time I've ever seen. I think it's probably trying to decompile even when it can't find the references. I don't know, if I encounter with LdFtn again, I'll share. :) Thanks for your interest!

**Comment by Dentrax** [comment]
Visual Studio Update 15.6.4 fixes my build bug.

But this bug is still in the final release ILSpy version 3.1.0.3645-rc. Although the all references are in the same directory, ILSpy cannot find them.

**Comment by siegfriedpammer** [comment]
Any update on this issue? All the binaries you provided so far decompile properly on my system. Can this be closed?

**Comment by Dentrax** [comment]
I've compiled it bug-free. But I don't know what is fixed this issue. :( But I'm sure the problem isn't about the VS or ILSpy version. Thanks for your interest! :) Sure, can be closed. 👍

**Comment by siegfriedpammer** [comment]
You can get it from here: https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy_binaries.zip?branch=master&job=Configuration%3A+Release

**Comment by Dentrax** [comment]
It looks like it hasn't fixed yet. I think this bug is important for mono. You should check HeyzapTest.cs's InitHeyzap() function. How it decompiles properly in you?

**Comment by siegfriedpammer** [comment]
![grafik](https://user-images.githubusercontent.com/344204/40236222-1b8b19da-5aad-11e8-8cda-f42ee5b3b066.png)

It is decompiled properly... no error.

**Comment by Dentrax** [comment]
![hhhe](https://user-images.githubusercontent.com/16493751/40249914-40e1c532-5add-11e8-9eb1-8d0e8d923de7.PNG)

Is there something wrong? Why doesn't it work properly with me?

**Comment by siegfriedpammer** [comment]
Do you see a warning about unresolved references at the top? If so, could you please post the assembly load log? (Just click the "References" node just below the assembly node in the tree view.)

Mine looks like this:

```
// Referenced assemblies (in metadata order):
// UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.CoreModule.dll

// UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.AnimationModule.dll

// UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.Physics2DModule.dll

// mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\mscorlib.dll

// UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.UI.dll

// UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.TextRenderingModule.dll

// UnityEngine.Purchasing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.Purchasing.dll

// UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.AudioModule.dll

// UnityEngine.UIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.UIModule.dll

// UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.IMGUIModule.dll

// Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\Assembly-CSharp-firstpass.dll

// UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.ImageConversionModule.dll

// Stores, Version=1.0.6633.150, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\Stores.dll

// UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: C:\Users\Siegfried\Downloads\Issue1104\UnityEngine.UnityAnalyticsModule.dll
```

**Comment by Dentrax** [comment]
Here is mine: (with Admin privileges)

`// Detected Target-Framework-Id: 

// Referenced assemblies (in metadata order):
// UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.CoreModule.dll

// UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.AnimationModule.dll

// UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.Physics2DModule.dll

// mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\mscorlib.dll

// UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.UI.dll

// UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.TextRenderingModule.dll

// UnityEngine.Purchasing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.Purchasing.dll

// UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.AudioModule.dll

// UnityEngine.UIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.UIModule.dll

// UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.IMGUIModule.dll

// Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Found in Assembly List

// UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.ImageConversionModule.dll

// Stores, Version=1.0.6633.150, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\Stores.dll

// UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\_Coding-Corner_\Unity3D\CrackedSources\TrapDungeons2 1.61\UnityEngine.UnityAnalyticsModule.dll

`

**Comment by Dentrax** [comment]
Here is mine: (with Admin privileges)

```
// Detected Target-Framework-Id: 

// Referenced assemblies (in metadata order):
// UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.CoreModule.dll

// UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.AnimationModule.dll

// UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.Physics2DModule.dll

// mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\mscorlib.dll

// UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.UI.dll

// UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.TextRenderingModule.dll

// UnityEngine.Purchasing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.Purchasing.dll

// UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.AudioModule.dll

// UnityEngine.UIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.UIModule.dll

// UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.IMGUIModule.dll

// Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Found in Assembly List

// UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.ImageConversionModule.dll

// Stores, Version=1.0.6633.150, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\Stores.dll

// UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
	// Assembly reference loading information:
	// Info: Success - Loading from: D:\Unity3D\TrapDungeons2 1.61\UnityEngine.UnityAnalyticsModule.dll

```

**Comment by siegfriedpammer** [comment]
The only difference I can see: `Assembly-CSharp-firstpass.dll` was found in the assembly list. Please try to remove this assembly from the treeview. It will be loaded automatically by ILSpy from the correct location.

The delegate type `HZIncentivizedAd.AdDisplayListener` used for the lambda in `InitHeyzap` is located in `Assembly-CSharp-firstpass.dll`. The version of  `Assembly-CSharp-firstpass.dll` found in your assembly list might be from a different Unity game and thus not contain the requested type. Which makes decompilation fail, because the type was not found.

Please remove the `Assembly-CSharp-firstpass.dll` from your assembly list and refresh the decompiler view. I would advise you to remove all loaded assemblies from the list when trying to decompile a Unity game, because Unity uses the same assembly names for each game, which will confuse the assembly resolver.

Please note that this behavior (first looking at the loaded assemblies, if that fails try to resolve the assembly name in the local directory) is expected: It is a performance optimization, so that we avoid disk IO if an assembly is already loaded. It also makes it possible to resolve assembly resolution errors (i.e. the assembly resolver picks the wrong assembly) can be resolved by manually loading the assembly in ILSpy.

Hope this helps!

**Comment by siegfriedpammer** [comment]
Addedum: I can imagine why dnSpy was decompiling the assembly correctly: Either assembly resolution works differently there or you did not have an assembly with the same name already loaded in your list.

Mystery solved! :)

**Comment by Dentrax** [comment]
Oh, thank you so much! You're right. I'd removed all assembly libraries called `Assembly-CSharp-firstpass.dll` And decompilation finished successfully. (except gotos, i guess that different mono stuff) 

Can we do a solution for this bug:
If we have more than one assembly file need to load (like `Assembly-CSharp-firstpass.dll` example), The assembly file that should be loaded even if it is there (assembly list), load it in the directory if it exists. If they all fail, ILSpy should load them all one at a time from assembly list and see if it's right. If it's not true, load the other, keep going like this... 
Can it be done like this?

**Comment by Dentrax** [comment]
If it wasn't too technical, I knew what you said. :) Thank you so much for your help. Also I hope the goto bug is solved soon.

-Closed
